// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkHub.DataAccess.Data;

#nullable disable

namespace WorkHub.DataAccess.Migrations
{
    [DbContext(typeof(WorkHubDbContext))]
    partial class WorkHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkHub.Models.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("int");

                    b.Property<int>("SeekerId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC077AFC05A6");

                    b.HasIndex("RecruitmentId");

                    b.HasIndex(new[] { "SeekerId", "RecruitmentId" }, "UQ_Application")
                        .IsUnique();

                    b.ToTable("Application");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyIndustry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogoUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CompanySize")
                        .HasColumnType("int");

                    b.Property<string>("CompanyWebUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__Company__3214EC070F87BB5D");

                    b.ToTable("Company");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Employer__3214EC07E3EE2679");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Employer");
                });

            modelBuilder.Entity("WorkHub.Models.Models.RecruitmentInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salary")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Schedule")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id")
                        .HasName("PK__Recruitm__3214EC0755D60B5E");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EmployerId");

                    b.ToTable("RecruitmentInfo");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Seeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Major")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Schedule")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Seeker__3214EC072FF42672");

                    b.HasIndex("UserId");

                    b.ToTable("Seeker");
                });

            modelBuilder.Entity("WorkHub.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(12)
                        .IsUnicode(false)
                        .HasColumnType("varchar(12)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__User__3214EC0794ADE483");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D1053491BE2FC7")
                        .IsUnique();

                    b.ToTable("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Application", b =>
                {
                    b.HasOne("WorkHub.Models.Models.RecruitmentInfo", "Recruitment")
                        .WithMany("Applications")
                        .HasForeignKey("RecruitmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Application_Recruitment");

                    b.HasOne("WorkHub.Models.Models.Seeker", "Seeker")
                        .WithMany("Applications")
                        .HasForeignKey("SeekerId")
                        .IsRequired()
                        .HasConstraintName("FK_Application_Seeker");

                    b.Navigation("Recruitment");

                    b.Navigation("Seeker");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Employer", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Company", "Company")
                        .WithMany("Employers")
                        .HasForeignKey("CompanyId")
                        .HasConstraintName("FK_Employer_Company");

                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("Employers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Employer_User");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.RecruitmentInfo", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Company", "Company")
                        .WithMany("RecruitmentInfos")
                        .HasForeignKey("CompanyId")
                        .IsRequired()
                        .HasConstraintName("FK_Recruitment_Company");

                    b.HasOne("WorkHub.Models.Models.Employer", "Employer")
                        .WithMany("RecruitmentInfos")
                        .HasForeignKey("EmployerId")
                        .IsRequired()
                        .HasConstraintName("FK_Recruitment_Employer");

                    b.Navigation("Company");

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Seeker", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("Seekers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Seeker_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Company", b =>
                {
                    b.Navigation("Employers");

                    b.Navigation("RecruitmentInfos");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Employer", b =>
                {
                    b.Navigation("RecruitmentInfos");
                });

            modelBuilder.Entity("WorkHub.Models.Models.RecruitmentInfo", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Seeker", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("WorkHub.Models.Models.User", b =>
                {
                    b.Navigation("Employers");

                    b.Navigation("Seekers");
                });
#pragma warning restore 612, 618
        }
    }
}
