// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkHub.DataAccess.Data;

#nullable disable

namespace WorkHub.DataAccess.Migrations
{
    [DbContext(typeof(WorkHubDbContext))]
    partial class WorkHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkHub.Models.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverLetter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("New");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Applicat__3214EC0709DB1FF3");

                    b.HasIndex("RecruitmentId");

                    b.HasIndex(new[] { "UserId" }, "IX_Application_UserId");

                    b.HasIndex(new[] { "UserId", "RecruitmentId" }, "UQ_Application")
                        .IsUnique();

                    b.ToTable("Application", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("WorkHub.Models.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Remote"
                        },
                        new
                        {
                            Id = 2,
                            Name = "An Giang"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ba Ria - Vung Tau"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bac Lieu"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bac Giang"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bac Kan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bac Ninh"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ben Tre"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Binh Duong"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Binh Dinh"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Binh Phuoc"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Binh Thuan"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Ca Mau"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Cao Bang"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Can Tho"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Da Nang"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Dak Lak"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Dak Nong"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Dien Bien"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Dong Nai"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Dong Thap"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Gia Lai"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Ha Giang"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Ha Nam"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Ha Noi"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ha Tinh"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Hai Duong"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Hai Phong"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Hau Giang"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Hoa Binh"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Hung Yen"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Khanh Hoa"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Kien Giang"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Kon Tum"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Lai Chau"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Lang Son"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Lao Cai"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Lam Dong"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Long An"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Nam Dinh"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Nghe An"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Ninh Binh"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Ninh Thuan"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Phu Tho"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Phu Yen"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Quang Binh"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Quang Nam"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Quang Ngai"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Quang Ninh"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Quang Tri"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Soc Trang"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Son La"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Tay Ninh"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Thai Binh"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Thai Nguyen"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Thanh Hoa"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Thua Thien Hue"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Tien Giang"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Tra Vinh"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Tuyen Quang"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Vinh Long"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Vinh Phuc"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Yen Bai"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Ho Chi Minh City"
                        });
                });

            modelBuilder.Entity("WorkHub.Models.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Comment__3214EC0788A5562F");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "PostId" }, "IX_Comment_PostId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.CommentLikes", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("CommentLikes");
                });

            modelBuilder.Entity("WorkHub.Models.Models.JobType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobTypes");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("PostImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Post__3214EC07971C2B27");

                    b.HasIndex(new[] { "UserId" }, "IX_Post_UserId");

                    b.ToTable("Post", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.PostLike", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserId", "PostId");

                    b.HasIndex("PostId");

                    b.ToTable("PostLike", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.PostRecruitment", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("RecruitmentId")
                        .HasColumnType("int");

                    b.HasKey("PostId", "RecruitmentId");

                    b.HasIndex("RecruitmentId");

                    b.ToTable("PostRecruitment", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.Recruitment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("JobName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("MaxSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Requirements")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SalaryCycle")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WorkTime")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__Recruitm__3214EC079D1054A4");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("JobTypeId");

                    b.HasIndex(new[] { "UserId" }, "IX_Recruitment_UserId");

                    b.ToTable("Recruitment", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportedUserId")
                        .HasColumnType("int");

                    b.Property<int>("ReporterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReportedUserId");

                    b.HasIndex("ReporterId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WorkHub.Models.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailVerificationToken")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportCount")
                        .HasColumnType("int");

                    b.Property<int?>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC0775A0391A");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534D3D212FF")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CvUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GoogleMapsEmbedUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndustryFocus")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobPreference")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double?>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__UserDeta__3214EC073F2B3337");

                    b.HasIndex(new[] { "UserId" }, "UQ__UserDeta__1788CC4D395EC6B9")
                        .IsUnique();

                    b.ToTable("UserDetail", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartYear")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEducations");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserExperiences");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserFollow", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.HasKey("FollowerId", "FollowingId")
                        .HasName("PK__UserFoll__79CB03351636060D");

                    b.HasIndex("FollowingId");

                    b.ToTable("UserFollow", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserNotification", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId", "NotificationId");

                    b.HasIndex("NotificationId");

                    b.ToTable("UserNotification", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__UserSche__3214EC072EF4856D");

                    b.HasIndex("UserId");

                    b.ToTable("UserSchedule", (string)null);
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Plan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("free");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Application", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Recruitment", "Recruitment")
                        .WithMany("Applications")
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__Recru__52593CB8");

                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Applicati__UserI__5165187F");

                    b.Navigation("Recruitment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Comment", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Comment", "ParentComment")
                        .WithMany("InverseParentComment")
                        .HasForeignKey("ParentCommentId")
                        .HasConstraintName("FK__Comment__ParentC__47DBAE45");

                    b.HasOne("WorkHub.Models.Models.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Comment__PostId__45F365D3");

                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Comment__UserId__46E78A0C");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.CommentLikes", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Comment", "Comment")
                        .WithMany("CommentLikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("CommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Order", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Post", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Post__UserId__4222D4EF");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.PostLike", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Post", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostLike_Post");

                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_PostLike_User");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.PostRecruitment", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Post", "Post")
                        .WithMany("PostRecruitments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkHub.Models.Models.Recruitment", "Recruitment")
                        .WithMany("PostRecruitments")
                        .HasForeignKey("RecruitmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Recruitment");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Recruitment", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Category", "Category")
                        .WithMany("Recruitments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkHub.Models.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("WorkHub.Models.Models.JobType", "JobType")
                        .WithMany("Recruitments")
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("Recruitments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("JobType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Report", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "ReportedUser")
                        .WithMany("ReportsReceived")
                        .HasForeignKey("ReportedUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WorkHub.Models.Models.User", "Reporter")
                        .WithMany("ReportsGiven")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ReportedUser");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserDetail", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithOne("UserDetail")
                        .HasForeignKey("WorkHub.Models.Models.UserDetail", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserDetai__UserI__3E52440B");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserEducation", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("UserEducations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserExperience", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("UserExperiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserFollow", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "Follower")
                        .WithMany("UserFollowFollowers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserFollo__Follo__571DF1D5");

                    b.HasOne("WorkHub.Models.Models.User", "Following")
                        .WithMany("UserFollowFollowings")
                        .HasForeignKey("FollowingId")
                        .IsRequired()
                        .HasConstraintName("FK__UserFollo__Follo__5812160E");

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserNotification", b =>
                {
                    b.HasOne("WorkHub.Models.Models.Notification", "Notification")
                        .WithMany("UserNotifications")
                        .HasForeignKey("NotificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("UserNotifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Notification");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserSchedule", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithMany("UserSchedules")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserSched__UserI__619B8048");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.UserSubscription", b =>
                {
                    b.HasOne("WorkHub.Models.Models.User", "User")
                        .WithOne("Subscription")
                        .HasForeignKey("WorkHub.Models.Models.UserSubscription", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Category", b =>
                {
                    b.Navigation("Recruitments");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Comment", b =>
                {
                    b.Navigation("CommentLikes");

                    b.Navigation("InverseParentComment");
                });

            modelBuilder.Entity("WorkHub.Models.Models.JobType", b =>
                {
                    b.Navigation("Recruitments");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Notification", b =>
                {
                    b.Navigation("UserNotifications");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PostLikes");

                    b.Navigation("PostRecruitments");
                });

            modelBuilder.Entity("WorkHub.Models.Models.Recruitment", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("PostRecruitments");
                });

            modelBuilder.Entity("WorkHub.Models.Models.User", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("CommentLikes");

                    b.Navigation("Comments");

                    b.Navigation("Orders");

                    b.Navigation("PostLikes");

                    b.Navigation("Posts");

                    b.Navigation("Recruitments");

                    b.Navigation("ReportsGiven");

                    b.Navigation("ReportsReceived");

                    b.Navigation("Subscription")
                        .IsRequired();

                    b.Navigation("UserDetail");

                    b.Navigation("UserEducations");

                    b.Navigation("UserExperiences");

                    b.Navigation("UserFollowFollowers");

                    b.Navigation("UserFollowFollowings");

                    b.Navigation("UserNotifications");

                    b.Navigation("UserSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
